const cardImages = {
    "AS": "https://deckofcardsapi.com/static/img/AS.png",
    "2S": "https://deckofcardsapi.com/static/img/2S.png",
    "3S": "https://deckofcardsapi.com/static/img/3S.png",
    "4S": "https://deckofcardsapi.com/static/img/4S.png",
    "5S": "https://deckofcardsapi.com/static/img/5S.png",
    "6S": "https://deckofcardsapi.com/static/img/6S.png",
    "7S": "https://deckofcardsapi.com/static/img/7S.png",
    "8S": "https://deckofcardsapi.com/static/img/8S.png",
    "9S": "https://deckofcardsapi.com/static/img/9S.png",
    "10S": "https://deckofcardsapi.com/static/img/0S.png",
    "JS": "https://deckofcardsapi.com/static/img/JS.png",
    "QS": "https://deckofcardsapi.com/static/img/QS.png",
    "KS": "https://deckofcardsapi.com/static/img/KS.png",
    
    "AH": "https://deckofcardsapi.com/static/img/AH.png",
    "2H": "https://deckofcardsapi.com/static/img/2H.png",
    "3H": "https://deckofcardsapi.com/static/img/3H.png",
    "4H": "https://deckofcardsapi.com/static/img/4H.png",
    "5H": "https://deckofcardsapi.com/static/img/5H.png",
    "6H": "https://deckofcardsapi.com/static/img/6H.png",
    "7H": "https://deckofcardsapi.com/static/img/7H.png",
    "8H": "https://deckofcardsapi.com/static/img/8H.png",
    "9H": "https://deckofcardsapi.com/static/img/9H.png",
    "10H": "https://deckofcardsapi.com/static/img/0H.png",
    "JH": "https://deckofcardsapi.com/static/img/JH.png",
    "QH": "https://deckofcardsapi.com/static/img/QH.png",
    "KH": "https://deckofcardsapi.com/static/img/KH.png",
    
    "AC": "https://deckofcardsapi.com/static/img/AC.png",
    "2C": "https://deckofcardsapi.com/static/img/2C.png",
    "3C": "https://deckofcardsapi.com/static/img/3C.png",
    "4C": "https://deckofcardsapi.com/static/img/4C.png",
    "5C": "https://deckofcardsapi.com/static/img/5C.png",
    "6C": "https://deckofcardsapi.com/static/img/6C.png",
    "7C": "https://deckofcardsapi.com/static/img/7C.png",
    "8C": "https://deckofcardsapi.com/static/img/8C.png",
    "9C": "https://deckofcardsapi.com/static/img/9C.png",
    "10C": "https://deckofcardsapi.com/static/img/0C.png",
    "JC": "https://deckofcardsapi.com/static/img/JC.png",
    "QC": "https://deckofcardsapi.com/static/img/QC.png",
    "KC": "https://deckofcardsapi.com/static/img/KC.png",
    
    "AD": "https://deckofcardsapi.com/static/img/AD.png",
    "2D": "https://deckofcardsapi.com/static/img/2D.png",
    "3D": "https://deckofcardsapi.com/static/img/3D.png",
    "4D": "https://deckofcardsapi.com/static/img/4D.png",
    "5D": "https://deckofcardsapi.com/static/img/5D.png",
    "6D": "https://deckofcardsapi.com/static/img/6D.png",
    "7D": "https://deckofcardsapi.com/static/img/7D.png",
    "8D": "https://deckofcardsapi.com/static/img/8D.png",
    "9D": "https://deckofcardsapi.com/static/img/9D.png",
    "10D": "https://deckofcardsapi.com/static/img/0D.png",
    "JD": "https://deckofcardsapi.com/static/img/JD.png",
    "QD": "https://deckofcardsapi.com/static/img/QD.png",
    "KD": "https://deckofcardsapi.com/static/img/KD.png"
};
